services:
  web:
    image: ${ECR_REPOSITORY}:web-${RELEASE}
    volumes:
      - static_volume:/app/lti/static
    env_file:
      - .env
    expose:
      - 8000
    restart:
      always
    command: /bin/sh -c "npm --prefix ./lti/frontend run dev & gunicorn costal.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - redis

  adaptive-engine:
    image: ${ECR_REPOSITORY}:adaptive-engine-${RELEASE}
    env_file:
      - .env
    ports:
      - "8001:8001"
    command: ["uvicorn", "adaptive-engine-api.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./devops/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/static
    depends_on:
      - web

volumes:
  static_volume:
