# Generated by Django 5.1 on 2024-10-01 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CanvasUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=200)),
                ('refresh_token', models.CharField(max_length=255, null=True)),
                ('expires_in', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deployment_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.TextField()),
                ('private_key', models.TextField()),
                ('alg', models.TextField(default='RS256')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=200)),
                ('teachers', models.ManyToManyField(related_name='teaching_courses', to='lti.canvasuser')),
                ('users', models.ManyToManyField(to='lti.canvasuser')),
            ],
        ),
        migrations.CreateModel(
            name='KeySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keys', models.ManyToManyField(blank=True, related_name='key_sets', to='lti.key')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuer', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=255)),
                ('platform_login_auth_endpoint', models.CharField(max_length=255)),
                ('platform_service_auth_endpoint', models.CharField(max_length=255)),
                ('platform_jwks_endpoint', models.CharField(max_length=255)),
                ('deployments', models.ManyToManyField(blank=True, related_name='registrations', to='lti.deployment')),
                ('key_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='lti.keyset')),
            ],
        ),
        migrations.AddField(
            model_name='deployment',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lti.registration'),
        ),
        migrations.AddConstraint(
            model_name='registration',
            constraint=models.UniqueConstraint(fields=('issuer', 'client_id'), name='unique_issuer_client_id'),
        ),
    ]
