# Generated by Django 5.1 on 2025-01-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti', '0002_assignment_end_date_assignment_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assessment_type',
            field=models.TextField(default='Homework'),
        ),
    ]
