# Generated by Django 5.1 on 2025-01-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti', '0003_assignment_assessment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='Course', max_length=255),
        ),
    ]
