# Generated by Django 5.1 on 2025-01-13 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti', '0003_possibleanswers_remove_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='num_points',
            field=models.IntegerField(default=1),
        ),
    ]
