# Generated by Django 5.1 on 2024-12-19 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti', '0003_possibleanswers_remove_course_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_seconds_to_answer', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lti.question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lti.possibleanswers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lti.canvasuser')),
            ],
        ),
    ]
