# Generated by Django 5.1 on 2024-12-23 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti', '0004_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='objectives',
        ),
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lti.objective'),
        ),
    ]
