# Generated by Django 5.1 on 2025-02-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti', '0005_module_assignment_associated_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.TextField(default='Multiple Choice'),
        ),
    ]
