# Generated by Django 5.1 on 2024-12-23 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti', '0005_remove_question_objectives_question_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='objectives',
        ),
        migrations.RemoveField(
            model_name='question',
            name='chapter',
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.TextField()),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lti.course')),
                ('questions', models.ManyToManyField(blank=True, to='lti.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='associated_skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lti.skill'),
        ),
        migrations.DeleteModel(
            name='Objective',
        ),
    ]
