# Generated by Django 5.1 on 2025-02-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti', '0006_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.TextField(default='multiple'),
        ),
    ]
