# Generated by Django 5.1 on 2025-02-09 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti', '0007_alter_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='skills',
            field=models.ManyToManyField(blank=True, to='lti.skill'),
        ),
    ]
