# Generated by Django 5.1 on 2025-03-09 21:27

import lti.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti', '0008_module_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='deadline',
            field=models.CharField(choices=[(lti.models.DeadlineType['WEEK'], 'WEEK'), (lti.models.DeadlineType['MONTH'], 'MONTH'), (lti.models.DeadlineType['END_OF_SESSION'], 'END_OF_SESSION')], default='WEEK', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='late_completion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='partial_completion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='penalty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
