# Generated by Django 5.1 on 2025-03-16 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lti", "0009_course_deadline_course_late_completion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prequiz",
            fields=[
                (
                    "assignment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="lti.assignment",
                    ),
                ),
            ],
            bases=("lti.assignment",),
        ),
        migrations.AddField(
            model_name="module",
            name="prequiz",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lti.prequiz",
            ),
        ),
    ]
