# Generated by Django 5.1 on 2025-03-10 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti', '0009_course_deadline_course_late_completion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_for_question_attempt', models.IntegerField(default=0)),
                ('is_correct', models.BooleanField(default=False)),
                ('time_spent_on_question', models.IntegerField(default=0)),
                ('associated_question', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lti.question')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_grade', models.IntegerField(default=0)),
                ('total_time_spent', models.IntegerField(default=0)),
                ('current_question_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lti.question')),
                ('attempted_questions', models.ManyToManyField(blank=True, to='lti.questionattempt')),
            ],
        ),
    ]
