# Generated by Django 5.1 on 2025-03-10 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti', '0010_questionattempt_assignmentattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lti.canvasuser'),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='student_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lti.canvasuser'),
        ),
    ]
