# Generated by Django 5.1 on 2025-03-10 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti', '0011_assignmentattempt_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentattempt',
            name='associated_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lti.assignment'),
        ),
    ]
