# Generated by Django 5.1 on 2025-03-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti', '0012_assignmentattempt_associated_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentattempt',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Not Started'), (1, 'Ongoing'), (2, 'Complete')], default=0),
        ),
    ]
