# Generated by Django 5.1 on 2025-03-16 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti', '0013_assignmentattempt_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionattempt',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='questionattempt',
            name='student_response',
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='associated_possible_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lti.possibleanswer'),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='number_of_hints',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Response',
        ),
    ]
