# Generated by Django 5.1 on 2025-03-16 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti', '0014_remove_questionattempt_is_correct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prequiz',
            fields=[
                ('assignment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='lti.assignment')),
            ],
            bases=('lti.assignment',),
        ),
        migrations.AddField(
            model_name='module',
            name='prequiz',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lti.prequiz'),
        ),
    ]
