# Generated by Django 5.1 on 2025-03-17 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lti', '0015_prequiz_module_prequiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='associated_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lti.assignment'),
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='associated_assignment_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lti.assignmentattempt'),
        ),
        migrations.AlterField(
            model_name='questionattempt',
            name='associated_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lti.question'),
        ),
    ]
