# Generated by Django 5.1 on 2025-03-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lti", "0016_questionattempt_associated_assignment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentattempt",
            name="completion_percentage",
            field=models.FloatField(default=0.0),
        ),
    ]
