# Generated by Django 5.1 on 2025-03-26 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lti", "0017_assignmentattempt_completion_percentage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="prequiz",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="lti.prequiz",
            ),
        ),
    ]
