# Generated by Django 5.1 on 2025-03-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lti", "0017_assignmentattempt_completion_percentage"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="canvas_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
