# Generated by Django 5.1 on 2025-03-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lti", "0019_questionattempt_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentattempt",
            name="total_grade",
            field=models.FloatField(default=0.0),
        ),
    ]
