# Generated by Django 5.1 on 2025-03-27 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lti", "0022_question_explanation"),
    ]

    operations = [
        migrations.AddField(
            model_name="textbook",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="lti.course",
            ),
        ),
    ]
