# Generated by Django 5.1 on 2025-04-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lti", "0023_textbook_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="is_math",
            field=models.BooleanField(default=False),
        ),
    ]
